apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: console-hpa
  labels:
    app: nitroboost-console
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: console-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10