apiVersion: v1
kind: Service
metadata:
  name: Production
  namespace: nitroboost
spec:
  type: LoadBalancer
  selector:
    app: Production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080